// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import fs from "node:fs";
import path from "node:path";
import dotenv from "dotenv";
import { defineConfig } from "prisma/config";

const cwd = process.cwd();
const envPath = path.resolve(cwd, ".env");
dotenv.config({ path: envPath });

const prismaConfigUrl = process.env["DATABASE_URL"];
if (process.env.PRISMA_DEBUG_DATABASE_URL === "1") {
  const masked = (prismaConfigUrl ?? "").replace(
    /(postgres(?:ql)?:\/\/)([^:@]+)(?::[^@]*)?@/i,
    "$1$2:***@",
  );
  console.info("[prisma-config] cwd =", cwd);
  console.info("[prisma-config] envPath =", envPath);
  console.info("[prisma-config] envExists =", fs.existsSync(envPath));
  console.info("[prisma-config] DATABASE_URL =", masked || "<empty>");
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: prismaConfigUrl,
  },
});
